import { mkdirSync, mkdtempSync, realpathSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, ruleTester } from "../rule-tester";
import { sharedStyleDedupRule } from "./shared-style-dedup";

/**
 * The rule compares className lists across the whole tree, so the fixture is a
 * real project. Node runs each test file in its own process, which makes the
 * `chdir` below safe.
 */
const FIXTURE: Record<string, string> = {
  // Two components share the same combination: it must become a custom utility.
  "features/billing/bill-summary.tsx":
    'export function BillSummary() { return <div className="bg-primary-canvas text-primary-ink" />; }\n',
  "features/billing/payment-summary.tsx":
    'export function PaymentSummary() { return <div className="bg-primary-canvas text-primary-ink" />; }\n',

  // A combination used by only one component stays local.
  "features/stream/stream-player.tsx":
    'export function StreamPlayer() { return <div className="rounded-lg p-4 shadow-sm" />; }\n',
};

const root = realpathSync(mkdtempSync(path.join(tmpdir(), "pasika-shared-style-")));
for (const [relativePath, contents] of Object.entries(FIXTURE)) {
  const filePath = path.join(root, "src", relativePath);
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, contents);
}
process.chdir(root);

const file = (relativePath: string): string => path.join(root, "src", relativePath);
const read = (relativePath: string): string => FIXTURE[relativePath] ?? "";

const DOC = "See docs/next-tailwind-guide/rules/theme-and-utility-definition-rule.md";

void describe(
  "A style or group of styles that two or more components use together and should change together MUST become one named custom utility. The group MAY include utilities generated by theme variables, built-in utilities, other custom utilities, and interaction styles.",
  () => {
    ruleTester.run("shared-style-dedup", sharedStyleDedupRule, {
      valid: [
        // The report lands once, on the alphabetically first user.
        {
          code: read("features/billing/payment-summary.tsx"),
          filename: file("features/billing/payment-summary.tsx"),
        },
        // A combination used by one component is not shared.
        {
          code: read("features/stream/stream-player.tsx"),
          filename: file("features/stream/stream-player.tsx"),
        },
      ],
      invalid: [
        {
          code: read("features/billing/bill-summary.tsx"),
          filename: file("features/billing/bill-summary.tsx"),
          errors: [
            {
              message:
              `Class combination "bg-primary-canvas text-primary-ink" is used by 2 components and should change together; create a named custom Tailwind utility for it. ${DOC}`,
            },
          ],
        },
      ],
    });
  },
);

void describe(
  "Styling used by only one component MUST stay in that component file as static Tailwind utility classes and MUST NOT be moved to the global stylesheet.",
  () => {
    ruleTester.run("shared-style-dedup", sharedStyleDedupRule, {
      valid: [
        // Single-component styling stays local: no extraction report.
        {
          code: read("features/stream/stream-player.tsx"),
          filename: file("features/stream/stream-player.tsx"),
        },
      ],
      invalid: [],
    });
  },
);
